RAW_PATTERNS: list[dict] = [

    ##################################################################
    ##           Support the project by adding a pattern            ##
    ##################################################################
    
    {
        "id": 'aws_access_key_id',
        "regex": r'AKIA[0-9A-Z]{16}',
        "description": 'AWS Access Key ID',
        "severity": 'critical',
        "tags": ['aws', 'cloud'],
    },
    {
        "id": 'aws_secret_access_key',
        "regex": r'(?i)aws.{0,20}secret.{0,20}[\'\\"]([0-9a-zA-Z/+]{40})[\'\\"]',
        "description": 'AWS Secret Access Key',
        "severity": 'critical',
        "tags": ['aws', 'cloud'],
    },
    {
        "id": 'aws_session_token',
        "regex": r'(?i)aws.{0,20}session.{0,20}token.{0,20}[\'\\"]([A-Za-z0-9/+=]{100,})[\'\\"]',
        "description": 'AWS Session Token',
        "severity": 'critical',
        "tags": ['aws', 'cloud'],
    },
    {
        "id": 'aws_mws_key',
        "regex": r'amzn\\.mws\\.[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}',
        "description": 'AWS MWS Key',
        "severity": 'critical',
        "tags": ['aws', 'cloud'],
    },
    {
        "id": 'aws_s3_bucket_url',
        "regex": r's3\\.amazonaws\\.com[/]+|[a-zA-Z0-9_-]*\\.s3\\.amazonaws\\.com',
        "description": 'AWS S3 Bucket URL (possible exposed bucket)',
        "severity": 'medium',
        "tags": ['aws', 'cloud'],
    },
    {
        "id": 'google_api_key',
        "regex": r'AIza[0-9A-Za-z\\-_]{35}',
        "description": 'Google API Key',
        "severity": 'critical',
        "tags": ['google', 'cloud'],
    },
    {
        "id": 'google_oauth_client_id',
        "regex": r'[0-9]+-[0-9A-Za-z_]{32}\\.apps\\.googleusercontent\\.com',
        "description": 'Google OAuth Client ID',
        "severity": 'high',
        "tags": ['google', 'oauth'],
    },
    {
        "id": 'google_oauth_client_secret',
        "regex": r'(?i)google.{0,20}client.{0,20}secret.{0,20}[\'\\"]([A-Za-z0-9\\-_]{24})[\'\\"]',
        "description": 'Google OAuth Client Secret',
        "severity": 'critical',
        "tags": ['google', 'oauth'],
    },
    {
        "id": 'google_service_account',
        "regex": r'\\"type\\"\\s*:\\s*\\"service_account\\"',
        "description": 'Google Service Account JSON',
        "severity": 'critical',
        "tags": ['google', 'cloud'],
    },
    {
        "id": 'gcp_private_key_id',
        "regex": r'\\"private_key_id\\"\\s*:\\s*\\"[a-f0-9]{40}\\"',
        "description": 'GCP Private Key ID',
        "severity": 'critical',
        "tags": ['google', 'cloud'],
    },
    {
        "id": 'firebase_api_key',
        "regex": r'(?i)firebase.{0,20}[\'\\"]AIza[0-9A-Za-z\\-_]{35}[\'\\"]',
        "description": 'Firebase API Key',
        "severity": 'critical',
        "tags": ['google', 'firebase'],
    },
    {
        "id": 'firebase_url',
        "regex": r'https://[a-z0-9-]+\\.firebaseio\\.com',
        "description": 'Firebase Database URL',
        "severity": 'medium',
        "tags": ['google', 'firebase'],
    },
    {
        "id": 'azure_storage_key',
        "regex": r'(?i)DefaultEndpointsProtocol=https?;AccountName=[^;]+;AccountKey=[A-Za-z0-9+/=]{88}',
        "description": 'Azure Storage Connection String',
        "severity": 'critical',
        "tags": ['azure', 'cloud'],
    },
    {
        "id": 'azure_client_secret',
        "regex": r'(?i)azure.{0,20}client.{0,20}secret.{0,20}[\'\\"]([A-Za-z0-9~._\\-]{34,40})[\'\\"]',
        "description": 'Azure Client Secret',
        "severity": 'critical',
        "tags": ['azure', 'cloud'],
    },
    {
        "id": 'azure_sas_token',
        "regex": r'(?i)sig=[A-Za-z0-9%]{20,}',
        "description": 'Azure SAS Token',
        "severity": 'high',
        "tags": ['azure', 'cloud'],
    },
    {
        "id": 'azure_subscription_key',
        "regex": r'(?i)Ocp-Apim-Subscription-Key[\'\\"]?\\s*[:=]\\s*[\'\\"]?([a-f0-9]{32})[\'\\"]?',
        "description": 'Azure Cognitive Services Key',
        "severity": 'critical',
        "tags": ['azure', 'cloud'],
    },
    {
        "id": 'github_personal_access_token',
        "regex": r'ghp_[0-9a-zA-Z]{36}',
        "description": 'GitHub Personal Access Token',
        "severity": 'critical',
        "tags": ['github', 'vcs'],
    },
    {
        "id": 'github_oauth_token',
        "regex": r'gho_[0-9a-zA-Z]{36}',
        "description": 'GitHub OAuth Token',
        "severity": 'critical',
        "tags": ['github', 'vcs'],
    },
    {
        "id": 'github_app_token',
        "regex": r'(ghu|ghs)_[0-9a-zA-Z]{36}',
        "description": 'GitHub App Token',
        "severity": 'critical',
        "tags": ['github', 'vcs'],
    },
    {
        "id": 'github_refresh_token',
        "regex": r'ghr_[0-9a-zA-Z]{76}',
        "description": 'GitHub Refresh Token',
        "severity": 'critical',
        "tags": ['github', 'vcs'],
    },
    {
        "id": 'github_actions_token',
        "regex": r'(?i)GITHUB_TOKEN\\s*=\\s*[\'\\"]([A-Za-z0-9_\\-]{20,})[\'\\"]',
        "description": 'GitHub Actions Token',
        "severity": 'high',
        "tags": ['github', 'vcs'],
    },
    {
        "id": 'gitlab_personal_access_token',
        "regex": r'glpat-[0-9a-zA-Z\\-_]{20}',
        "description": 'GitLab Personal Access Token',
        "severity": 'critical',
        "tags": ['gitlab', 'vcs'],
    },
    {
        "id": 'gitlab_pipeline_trigger_token',
        "regex": r'glptt-[0-9a-f]{40}',
        "description": 'GitLab Pipeline Trigger Token',
        "severity": 'high',
        "tags": ['gitlab', 'vcs'],
    },
    {
        "id": 'gitlab_runner_token',
        "regex": r'GR1348941[0-9a-zA-Z_\\-]{20}',
        "description": 'GitLab Runner Token',
        "severity": 'high',
        "tags": ['gitlab', 'vcs'],
    },
    {
        "id": 'openai_api_key',
        "regex": r'sk-[a-zA-Z0-9_-]{20,}',
        "description": 'OpenAI API Key',
        "severity": 'critical',
        "tags": ['ai', 'openai'],
    },
    {
        "id": 'openai_org_id',
        "regex": r'org-[0-9a-zA-Z]{24}',
        "description": 'OpenAI Organization ID',
        "severity": 'medium',
        "tags": ['ai', 'openai'],
    },
    {
        "id": 'anthropic_api_key',
        "regex": r'sk-ant-api03-[0-9a-zA-Z\\-_]{93}AA',
        "description": 'Anthropic API Key',
        "severity": 'critical',
        "tags": ['ai', 'anthropic'],
    },
    {
        "id": 'huggingface_token',
        "regex": r'hf_[0-9a-zA-Z]{34}',
        "description": 'HuggingFace API Token',
        "severity": 'critical',
        "tags": ['ai', 'huggingface'],
    },
    {
        "id": 'cohere_api_key',
        "regex": r'(?i)cohere.{0,20}[\'\\"]([A-Za-z0-9]{40})[\'\\"]',
        "description": 'Cohere API Key',
        "severity": 'critical',
        "tags": ['ai', 'cohere'],
    },
    {
        "id": 'replicate_api_key',
        "regex": r'r8_[0-9a-zA-Z]{37}',
        "description": 'Replicate API Key',
        "severity": 'critical',
        "tags": ['ai', 'replicate'],
    },
    {
        "id": 'stability_ai_key',
        "regex": r'sk-[0-9a-zA-Z]{48}(?=.*stability)',
        "description": 'Stability AI Key',
        "severity": 'critical',
        "tags": ['ai', 'stability'],
    },
    {
        "id": 'stripe_secret_key',
        "regex": r'sk_live_[0-9a-zA-Z]{24}',
        "description": 'Stripe Secret Key (Live)',
        "severity": 'critical',
        "tags": ['payment', 'stripe'],
    },
    {
        "id": 'stripe_test_key',
        "regex": r'sk_test_[0-9a-zA-Z]{24}',
        "description": 'Stripe Secret Key (Test)',
        "severity": 'high',
        "tags": ['payment', 'stripe'],
    },
    {
        "id": 'stripe_restricted_key',
        "regex": r'rk_live_[0-9a-zA-Z]{24}',
        "description": 'Stripe Restricted Key (Live)',
        "severity": 'critical',
        "tags": ['payment', 'stripe'],
    },
    {
        "id": 'stripe_webhook_secret',
        "regex": r'whsec_[0-9a-zA-Z]{32,}',
        "description": 'Stripe Webhook Secret',
        "severity": 'high',
        "tags": ['payment', 'stripe'],
    },
    {
        "id": 'paypal_client_secret',
        "regex": r'(?i)paypal.{0,20}secret.{0,20}[\'\\"]([A-Za-z0-9_\\-]{40,80})[\'\\"]',
        "description": 'PayPal Client Secret',
        "severity": 'critical',
        "tags": ['payment', 'paypal'],
    },
    {
        "id": 'braintree_access_token',
        "regex": r'access_token\\$production\\$[0-9a-z]{16}\\$[0-9a-f]{32}',
        "description": 'Braintree Access Token',
        "severity": 'critical',
        "tags": ['payment', 'braintree'],
    },
    {
        "id": 'square_access_token',
        "regex": r'sq0atp-[0-9A-Za-z\\-_]{22}',
        "description": 'Square Access Token',
        "severity": 'critical',
        "tags": ['payment', 'square'],
    },
    {
        "id": 'square_oauth_secret',
        "regex": r'sq0csp-[0-9A-Za-z\\-_]{43}',
        "description": 'Square OAuth Secret',
        "severity": 'critical',
        "tags": ['payment', 'square'],
    },
    {
        "id": 'iyzico_api_key',
        "regex": r'(?i)iyzico.{0,20}[\'\\"]([A-Za-z0-9]{32,})[\'\\"]',
        "description": 'Iyzico API Key',
        "severity": 'critical',
        "tags": ['payment', 'iyzico', 'turkey'],
    },
    {
        "id": 'paytr_merchant_key',
        "regex": r'(?i)paytr.{0,20}[\'\\"]([A-Za-z0-9]{32,})[\'\\"]',
        "description": 'PayTR Merchant Key',
        "severity": 'critical',
        "tags": ['payment', 'paytr', 'turkey'],
    },
    {
        "id": 'twitter_api_key',
        "regex": r'(?i)twitter.{0,20}[\'\\"]([A-Za-z0-9]{25})[\'\\"]',
        "description": 'Twitter API Key',
        "severity": 'high',
        "tags": ['social', 'twitter'],
    },
    {
        "id": 'twitter_bearer_token',
        "regex": r'AAAAAAAAAA[0-9a-zA-Z%]{50,}',
        "description": 'Twitter Bearer Token',
        "severity": 'high',
        "tags": ['social', 'twitter'],
    },
    {
        "id": 'twitter_access_token',
        "regex": r'(?i)twitter.{0,20}access.{0,20}token.{0,20}[\'\\"]([A-Za-z0-9\\-]{50,})[\'\\"]',
        "description": 'Twitter Access Token',
        "severity": 'high',
        "tags": ['social', 'twitter'],
    },
    {
        "id": 'facebook_access_token',
        "regex": r'EAACEdEose0cBA[0-9A-Za-z]+',
        "description": 'Facebook Access Token',
        "severity": 'high',
        "tags": ['social', 'facebook'],
    },
    {
        "id": 'facebook_app_secret',
        "regex": r'(?i)facebook.{0,20}app.{0,20}secret.{0,20}[\'\\"]([a-f0-9]{32})[\'\\"]',
        "description": 'Facebook App Secret',
        "severity": 'critical',
        "tags": ['social', 'facebook'],
    },
    {
        "id": 'instagram_access_token',
        "regex": r'(?i)instagram.{0,20}[\'\\"]([A-Za-z0-9_]{50,})[\'\\"]',
        "description": 'Instagram Access Token',
        "severity": 'high',
        "tags": ['social', 'instagram'],
    },
    {
        "id": 'linkedin_client_secret',
        "regex": r'(?i)linkedin.{0,20}secret.{0,20}[\'\\"]([A-Za-z0-9]{16})[\'\\"]',
        "description": 'LinkedIn Client Secret',
        "severity": 'high',
        "tags": ['social', 'linkedin'],
    },
    {
        "id": 'discord_bot_token',
        "regex": r'(Bot\\s)?[MNO][A-Za-z\\d]{23}\\.[\\w-]{6}\\.[\\w-]{27}',
        "description": 'Discord Bot Token',
        "severity": 'critical',
        "tags": ['social', 'discord'],
    },
    {
        "id": 'discord_webhook',
        "regex": r'https://discord(?:app)?\\.com/api/webhooks/[0-9]{17,19}/[A-Za-z0-9_\\-]{60,68}',
        "description": 'Discord Webhook URL',
        "severity": 'high',
        "tags": ['social', 'discord'],
    },
    {
        "id": 'slack_bot_token',
        "regex": r'xoxb-[0-9]{11}-[0-9]{11}-[0-9a-zA-Z]{24}',
        "description": 'Slack Bot Token',
        "severity": 'critical',
        "tags": ['social', 'slack'],
    },
    {
        "id": 'slack_user_token',
        "regex": r'xoxp-[0-9]{11}-[0-9]{11}-[0-9]{11}-[0-9a-f]{32}',
        "description": 'Slack User Token',
        "severity": 'critical',
        "tags": ['social', 'slack'],
    },
    {
        "id": 'slack_webhook',
        "regex": r'https://hooks\\.slack\\.com/services/T[A-Z0-9]{8}/B[A-Z0-9]{8}/[A-Za-z0-9]{24}',
        "description": 'Slack Webhook URL',
        "severity": 'high',
        "tags": ['social', 'slack'],
    },
    {
        "id": 'slack_app_token',
        "regex": r'xapp-[0-9]-[A-Z0-9]{10}-[0-9]{13}-[a-z0-9]{64}',
        "description": 'Slack App Token',
        "severity": 'critical',
        "tags": ['social', 'slack'],
    },
    {
        "id": 'telegram_bot_token',
        "regex": r'[0-9]{8,10}:[A-Za-z0-9_\\-]{35}',
        "description": 'Telegram Bot Token',
        "severity": 'critical',
        "tags": ['social', 'telegram'],
    },
    {
        "id": 'youtube_api_key',
        "regex": r'(?i)youtube.{0,20}[\'\\"]AIza[0-9A-Za-z\\-_]{35}[\'\\"]',
        "description": 'YouTube API Key',
        "severity": 'high',
        "tags": ['social', 'youtube'],
    },
    {
        "id": 'tiktok_client_key',
        "regex": r'(?i)tiktok.{0,20}client.{0,20}key.{0,20}[\'\\"]([A-Za-z0-9]{18,})[\'\\"]',
        "description": 'TikTok Client Key',
        "severity": 'high',
        "tags": ['social', 'tiktok'],
    },
    {
        "id": 'sendgrid_api_key',
        "regex": r'SG\\.[0-9A-Za-z\\-_]{22}\\.[0-9A-Za-z\\-_]{43}',
        "description": 'SendGrid API Key',
        "severity": 'critical',
        "tags": ['email', 'sendgrid'],
    },
    {
        "id": 'mailgun_api_key',
        "regex": r'key-[0-9a-zA-Z]{32}',
        "description": 'Mailgun API Key',
        "severity": 'critical',
        "tags": ['email', 'mailgun'],
    },
    {
        "id": 'mailchimp_api_key',
        "regex": r'[0-9a-f]{32}-us[0-9]{1,2}',
        "description": 'Mailchimp API Key',
        "severity": 'critical',
        "tags": ['email', 'mailchimp'],
    },
    {
        "id": 'postmark_api_key',
        "regex": r'(?i)postmark.{0,20}[\'\\"]([A-Za-z0-9\\-]{36})[\'\\"]',
        "description": 'Postmark API Key',
        "severity": 'critical',
        "tags": ['email', 'postmark'],
    },
    {
        "id": 'twilio_account_sid',
        "regex": r'AC[0-9a-fA-F]{32}',
        "description": 'Twilio Account SID',
        "severity": 'high',
        "tags": ['sms', 'twilio'],
    },
    {
        "id": 'twilio_auth_token',
        "regex": r'(?i)twilio.{0,20}auth.{0,20}token.{0,20}[\'\\"]([a-f0-9]{32})[\'\\"]',
        "description": 'Twilio Auth Token',
        "severity": 'critical',
        "tags": ['sms', 'twilio'],
    },
    {
        "id": 'vonage_api_key',
        "regex": r'(?i)vonage.{0,20}[\'\\"]([a-z0-9]{8})[\'\\"]',
        "description": 'Vonage API Key',
        "severity": 'high',
        "tags": ['sms', 'vonage'],
    },
    {
        "id": 'mongodb_connection_string',
        "regex": r'mongodb(\\+srv)?://[^:]+:[^@]+@[^\\s\\"\']+',
        "description": 'MongoDB Connection String',
        "severity": 'critical',
        "tags": ['database', 'mongodb'],
    },
    {
        "id": 'postgresql_connection_string',
        "regex": r'postgresql://[^:]+:[^@]+@[^\\s\\"\']+',
        "description": 'PostgreSQL Connection String',
        "severity": 'critical',
        "tags": ['database', 'postgresql'],
    },
    {
        "id": 'mysql_connection_string',
        "regex": r'mysql://[^:]+:[^@]+@[^\\s\\"\']+',
        "description": 'MySQL Connection String',
        "severity": 'critical',
        "tags": ['database', 'mysql'],
    },
    {
        "id": 'redis_connection_string',
        "regex": r'redis://[^:]*:[^@]+@[^\\s\\"\']+',
        "description": 'Redis Connection String (with password)',
        "severity": 'critical',
        "tags": ['database', 'redis'],
    },
    {
        "id": 'database_url',
        "regex": r'(?i)DATABASE_URL\\s*=\\s*[\'\\"]?[a-z]+://[^:]+:[^@]+@[^\\s\\"\']+[\'\\"]?',
        "description": 'Generic Database URL with credentials',
        "severity": 'critical',
        "tags": ['database'],
    },
    {
        "id": 'supabase_key',
        "regex": r'(?i)supabase.{0,20}[\'\\"]eyJ[A-Za-z0-9_\\-]{50,}[\'\\"]',
        "description": 'Supabase API Key',
        "severity": 'critical',
        "tags": ['database', 'supabase'],
    },
    {
        "id": 'planetscale_password',
        "regex": r'pscale_pw_[A-Za-z0-9_\\-]{43}',
        "description": 'PlanetScale Password',
        "severity": 'critical',
        "tags": ['database', 'planetscale'],
    },
    {
        "id": 'turso_auth_token',
        "regex": r'(?i)turso.{0,20}[\'\\"]([A-Za-z0-9_\\-\\.]{100,})[\'\\"]',
        "description": 'Turso Auth Token',
        "severity": 'critical',
        "tags": ['database', 'turso'],
    },
    {
        "id": 'neon_connection_string',
        "regex": r'postgres://[^:]+:[^@]+@[^.]+\\.neon\\.tech[^\\s\\"\']*',
        "description": 'Neon Database Connection String',
        "severity": 'critical',
        "tags": ['database', 'neon'],
    },
    {
        "id": 'rsa_private_key',
        "regex": r'-----BEGIN RSA PRIVATE KEY-----',
        "description": 'RSA Private Key',
        "severity": 'critical',
        "tags": ['crypto', 'key'],
    },
    {
        "id": 'ec_private_key',
        "regex": r'-----BEGIN EC PRIVATE KEY-----',
        "description": 'EC Private Key',
        "severity": 'critical',
        "tags": ['crypto', 'key'],
    },
    {
        "id": 'generic_private_key',
        "regex": r'-----BEGIN PRIVATE KEY-----',
        "description": 'Generic Private Key',
        "severity": 'critical',
        "tags": ['crypto', 'key'],
    },
    {
        "id": 'openssh_private_key',
        "regex": r'-----BEGIN OPENSSH PRIVATE KEY-----',
        "description": 'OpenSSH Private Key',
        "severity": 'critical',
        "tags": ['crypto', 'ssh'],
    },
    {
        "id": 'pgp_private_key',
        "regex": r'-----BEGIN PGP PRIVATE KEY BLOCK-----',
        "description": 'PGP Private Key Block',
        "severity": 'critical',
        "tags": ['crypto', 'pgp'],
    },
    {
        "id": 'pkcs12_certificate',
        "regex": r'-----BEGIN CERTIFICATE-----',
        "description": 'Certificate File',
        "severity": 'high',
        "tags": ['crypto', 'cert'],
    },
    {
        "id": 'jwt_token',
        "regex": r'eyJ[0-9a-zA-Z_\\-]{10,}\\.[0-9a-zA-Z_\\-]{10,}\\.[0-9a-zA-Z_\\-]{10,}',
        "description": 'JWT Token',
        "severity": 'high',
        "tags": ['auth', 'jwt'],
    },
    {
        "id": 'bearer_token',
        "regex": r'(?i)Bearer\\s+[A-Za-z0-9\\-_\\.]{20,}',
        "description": 'Bearer Token',
        "severity": 'high',
        "tags": ['auth', 'bearer'],
    },
    {
        "id": 'basic_auth_header',
        "regex": r'(?i)Authorization:\\s*Basic\\s+[A-Za-z0-9+/=]{20,}',
        "description": 'Basic Auth Header',
        "severity": 'critical',
        "tags": ['auth', 'basic'],
    },
    {
        "id": 'hardcoded_password',
        "regex": r'(?i)password\\s*[=:]\\s*[\'\\"][^\'\\"]{6,}[\'\\"]',
        "description": 'Hardcoded Password',
        "severity": 'critical',
        "tags": ['credential'],
    },
    {
        "id": 'hardcoded_passwd',
        "regex": r'(?i)passwd\\s*[=:]\\s*[\'\\"][^\'\\"]{6,}[\'\\"]',
        "description": 'Hardcoded Password (passwd)',
        "severity": 'critical',
        "tags": ['credential'],
    },
    {
        "id": 'hardcoded_secret',
        "regex": r'(?i)secret\\s*[=:]\\s*[\'\\"][^\'\\"]{8,}[\'\\"]',
        "description": 'Hardcoded Secret',
        "severity": 'critical',
        "tags": ['credential'],
    },
    {
        "id": 'hardcoded_api_key',
        "regex": r'(?i)api[_\\-]?key\\s*[=:]\\s*[\'\\"][^\'\\"]{10,}[\'\\"]',
        "description": 'Hardcoded API Key',
        "severity": 'critical',
        "tags": ['credential'],
    },
    {
        "id": 'hardcoded_token',
        "regex": r'(?i)token\\s*[=:]\\s*[\'\\"][A-Za-z0-9_\\-\\.]{20,}[\'\\"]',
        "description": 'Hardcoded Token',
        "severity": 'high',
        "tags": ['credential'],
    },
    {
        "id": 'hardcoded_auth',
        "regex": r'(?i)auth\\s*[=:]\\s*[\'\\"][^\'\\"]{10,}[\'\\"]',
        "description": 'Hardcoded Auth Value',
        "severity": 'high',
        "tags": ['credential'],
    },
    {
        "id": 'hardcoded_username_password',
        "regex": r'(?i)(username|user)\\s*[=:]\\s*[\'\\"][^\'\\"]+[\'\\"].{0,30}(password|passwd)\\s*[=:]\\s*[\'\\"][^\'\\"]{6,}[\'\\"]',
        "description": 'Username + Password combo',
        "severity": 'critical',
        "tags": ['credential'],
    },
    {
        "id": 'circleci_token',
        "regex": r'(?i)circleci.{0,20}[\'\\"]([A-Za-z0-9]{40})[\'\\"]',
        "description": 'CircleCI Token',
        "severity": 'critical',
        "tags": ['ci', 'circleci'],
    },
    {
        "id": 'travis_ci_token',
        "regex": r'(?i)travis.{0,20}[\'\\"]([A-Za-z0-9]{22})[\'\\"]',
        "description": 'Travis CI Token',
        "severity": 'critical',
        "tags": ['ci', 'travis'],
    },
    {
        "id": 'jenkins_api_token',
        "regex": r'(?i)jenkins.{0,20}[\'\\"]([A-Za-z0-9]{34})[\'\\"]',
        "description": 'Jenkins API Token',
        "severity": 'critical',
        "tags": ['ci', 'jenkins'],
    },
    {
        "id": 'vercel_token',
        "regex": r'(?i)vercel.{0,20}[\'\\"]([A-Za-z0-9]{24})[\'\\"]',
        "description": 'Vercel Token',
        "severity": 'critical',
        "tags": ['ci', 'vercel'],
    },
    {
        "id": 'netlify_token',
        "regex": r'(?i)netlify.{0,20}[\'\\"]([A-Za-z0-9_\\-]{40,})[\'\\"]',
        "description": 'Netlify Token',
        "severity": 'critical',
        "tags": ['ci', 'netlify'],
    },
    {
        "id": 'render_api_key',
        "regex": r'rnd_[A-Za-z0-9]{32}',
        "description": 'Render API Key',
        "severity": 'critical',
        "tags": ['ci', 'render'],
    },
    {
        "id": 'railway_token',
        "regex": r'(?i)railway.{0,20}[\'\\"]([A-Za-z0-9_\\-]{40,})[\'\\"]',
        "description": 'Railway Token',
        "severity": 'critical',
        "tags": ['ci', 'railway'],
    },
    {
        "id": 'cloudflare_api_key',
        "regex": r'(?i)cloudflare.{0,20}[\'\\"]([A-Za-z0-9_\\-]{37})[\'\\"]',
        "description": 'Cloudflare API Key',
        "severity": 'critical',
        "tags": ['hosting', 'cloudflare'],
    },
    {
        "id": 'cloudflare_global_api_key',
        "regex": r'(?i)cloudflare.{0,20}global.{0,20}[\'\\"]([a-f0-9]{37})[\'\\"]',
        "description": 'Cloudflare Global API Key',
        "severity": 'critical',
        "tags": ['hosting', 'cloudflare'],
    },
    {
        "id": 'digitalocean_token',
        "regex": r'(?i)digitalocean.{0,20}[\'\\"]([a-f0-9]{64})[\'\\"]',
        "description": 'DigitalOcean Token',
        "severity": 'critical',
        "tags": ['hosting', 'digitalocean'],
    },
    {
        "id": 'heroku_api_key',
        "regex": r'(?i)heroku.{0,20}[\'\\"]([0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12})[\'\\"]',
        "description": 'Heroku API Key',
        "severity": 'critical',
        "tags": ['hosting', 'heroku'],
    },
    {
        "id": 'linode_token',
        "regex": r'(?i)linode.{0,20}[\'\\"]([A-Za-z0-9]{64})[\'\\"]',
        "description": 'Linode API Token',
        "severity": 'critical',
        "tags": ['hosting', 'linode'],
    },
    {
        "id": 'sentry_dsn',
        "regex": r'https://[0-9a-f]{32}@[a-z0-9.]+\\.ingest\\.sentry\\.io/[0-9]+',
        "description": 'Sentry DSN',
        "severity": 'medium',
        "tags": ['monitoring', 'sentry'],
    },
    {
        "id": 'datadog_api_key',
        "regex": r'(?i)datadog.{0,20}[\'\\"]([a-f0-9]{32})[\'\\"]',
        "description": 'Datadog API Key',
        "severity": 'critical',
        "tags": ['monitoring', 'datadog'],
    },
    {
        "id": 'newrelic_license_key',
        "regex": r'NRAK-[A-Z0-9]{27}',
        "description": 'New Relic License Key',
        "severity": 'critical',
        "tags": ['monitoring', 'newrelic'],
    },
    {
        "id": 'mixpanel_token',
        "regex": r'(?i)mixpanel.{0,20}[\'\\"]([a-f0-9]{32})[\'\\"]',
        "description": 'Mixpanel Token',
        "severity": 'medium',
        "tags": ['analytics', 'mixpanel'],
    },
    {
        "id": 'amplitude_api_key',
        "regex": r'(?i)amplitude.{0,20}[\'\\"]([a-f0-9]{32})[\'\\"]',
        "description": 'Amplitude API Key',
        "severity": 'medium',
        "tags": ['analytics', 'amplitude'],
    },
    {
        "id": 'segment_write_key',
        "regex": r'(?i)segment.{0,20}write.{0,20}key.{0,20}[\'\\"]([A-Za-z0-9]{40,})[\'\\"]',
        "description": 'Segment Write Key',
        "severity": 'medium',
        "tags": ['analytics', 'segment'],
    },
    {
        "id": 'logrocket_app_id',
        "regex": r'(?i)logrocket.{0,20}[\'\\"]([a-z0-9]{6}/[a-z0-9\\-]+)[\'\\"]',
        "description": 'LogRocket App ID',
        "severity": 'low',
        "tags": ['monitoring', 'logrocket'],
    },
    {
        "id": 'turkish_tc_no',
        "regex": r'(?<!\\d)[1-9][0-9]{10}(?!\\d)',
        "description": 'Olası TC Kimlik Numarası',
        "severity": 'critical',
        "tags": ['pii', 'turkey', 'kvkk'],
    },
    {
        "id": 'credit_card_visa',
        "regex": r'4[0-9]{12}(?:[0-9]{3})?',
        "description": 'Visa Kredi Kartı Numarası',
        "severity": 'critical',
        "tags": ['pii', 'payment'],
    },
    {
        "id": 'credit_card_mastercard',
        "regex": r'5[1-5][0-9]{14}',
        "description": 'Mastercard Numarası',
        "severity": 'critical',
        "tags": ['pii', 'payment'],
    },
    {
        "id": 'credit_card_amex',
        "regex": r'3[47][0-9]{13}',
        "description": 'American Express Kart Numarası',
        "severity": 'critical',
        "tags": ['pii', 'payment'],
    },
    {
        "id": 'iban_turkish',
        "regex": r'TR\\d{2}\\s?\\d{4}\\s?\\d{4}\\s?\\d{4}\\s?\\d{4}\\s?\\d{4}\\s?\\d{2}',
        "description": 'Türk IBAN Numarası',
        "severity": 'critical',
        "tags": ['pii', 'turkey', 'banking'],
    },
    {
        "id": 'email_in_code',
        "regex": r'[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+',
        "description": 'E-posta Adress (Code hardcoded)',
        "severity": 'low',
        "tags": ['pii', 'email'],
    },
    {
        "id": 'ip_address_private',
        "regex": r'(?:192\\.168|10\\.|172\\.(?:1[6-9]|2[0-9]|3[01]))\\.[0-9]{1,3}\\.[0-9]{1,3}',
        "description": 'Hardcoded Private IP Address',
        "severity": 'low',
        "tags": ['network', 'ip'],
    },
    {
        "id": 'ssn_us',
        "regex": r'(?<!\\d)[0-9]{3}-[0-9]{2}-[0-9]{4}(?!\\d)',
        "description": 'US Social Security Number',
        "severity": 'critical',
        "tags": ['pii', 'us'],
    },
    {
        "id": 'mapbox_token',
        "regex": r'pk\\.eyJ1IjoiW[A-Za-z0-9_\\-]+\\.[A-Za-z0-9_\\-]+',
        "description": 'Mapbox Public Token',
        "severity": 'medium',
        "tags": ['maps', 'mapbox'],
    },
    {
        "id": 'mapbox_secret_token',
        "regex": r'sk\\.eyJ1IjoiW[A-Za-z0-9_\\-]+\\.[A-Za-z0-9_\\-]+',
        "description": 'Mapbox Secret Token',
        "severity": 'critical',
        "tags": ['maps', 'mapbox'],
    },
    {
        "id": 'algolia_api_key',
        "regex": r'(?i)algolia.{0,20}[\'\\"]([A-Za-z0-9]{32})[\'\\"]',
        "description": 'Algolia API Key',
        "severity": 'critical',
        "tags": ['search', 'algolia'],
    },
    {
        "id": 'pusher_app_key',
        "regex": r'(?i)pusher.{0,20}app.{0,20}key.{0,20}[\'\\"]([A-Za-z0-9]{20})[\'\\"]',
        "description": 'Pusher App Key',
        "severity": 'high',
        "tags": ['realtime', 'pusher'],
    },
    {
        "id": 'pusher_app_secret',
        "regex": r'(?i)pusher.{0,20}app.{0,20}secret.{0,20}[\'\\"]([A-Za-z0-9]{20})[\'\\"]',
        "description": 'Pusher App Secret',
        "severity": 'critical',
        "tags": ['realtime', 'pusher'],
    },
    {
        "id": 'shopify_secret',
        "regex": r'shpss_[A-Za-z0-9]{32}',
        "description": 'Shopify Secret Key',
        "severity": 'critical',
        "tags": ['ecommerce', 'shopify'],
    },
    {
        "id": 'shopify_access_token',
        "regex": r'shpat_[A-Za-z0-9]{32}',
        "description": 'Shopify Access Token',
        "severity": 'critical',
        "tags": ['ecommerce', 'shopify'],
    },
    {
        "id": 'npm_token',
        "regex": r'npm_[A-Za-z0-9]{36}',
        "description": 'NPM Token',
        "severity": 'critical',
        "tags": ['package', 'npm'],
    },
    {
        "id": 'pypi_token',
        "regex": r'pypi-[A-Za-z0-9_\\-]{50,}',
        "description": 'PyPI Token',
        "severity": 'critical',
        "tags": ['package', 'pypi'],
    },
    {
        "id": 'docker_hub_password',
        "regex": r'(?i)docker.{0,20}password.{0,20}[\'\\"]([^\'\\"]{8,})[\'\\"]',
        "description": 'Docker Hub Password',
        "severity": 'critical',
        "tags": ['docker', 'container'],
    },
    {
        "id": 'hashicorp_vault_token',
        "regex": r'hvs\\.[A-Za-z0-9]{24,}',
        "description": 'HashiCorp Vault Token',
        "severity": 'critical',
        "tags": ['secrets', 'vault'],
    },
    {
        "id": 'age_encryption_key',
        "regex": r'AGE-SECRET-KEY-[A-Z0-9]{59}',
        "description": 'Age Encryption Secret Key',
        "severity": 'critical',
        "tags": ['crypto', 'age'],
    },
    {
        "id": 'ipinfo_token',
        "regex": r'(?i)ipinfo.{0,20}[\'\\"]([A-Za-z0-9]{14})[\'\\"]',
        "description": 'IPInfo Token',
        "severity": 'medium',
        "tags": ['geo', 'ipinfo'],
    },
    {
        "id": 'weatherapi_key',
        "regex": r'(?i)weatherapi.{0,20}[\'\\"]([a-f0-9]{32})[\'\\"]',
        "description": 'WeatherAPI Key',
        "severity": 'medium',
        "tags": ['weather'],
    },
    {
        "id": 'rapidapi_key',
        "regex": r'(?i)rapidapi.{0,20}[\'\\"]([A-Za-z0-9]{50})[\'\\"]',
        "description": 'RapidAPI Key',
        "severity": 'critical',
        "tags": ['api', 'rapidapi'],
    },
    {
        "id": 'generic_high_entropy_secret',
        "regex": r'(?i)(secret|token|key|password|passwd|pwd|auth)\\s*[=:]\\s*[\'\\"]([A-Za-z0-9+/]{32,})[\'\\"]',
        "description": 'High entropy — likely a hidden value',
        "severity": 'medium',
        "tags": ['generic', 'entropy'],
    },

    ##################################################################
    ##           Support the project by adding a pattern            ##
    ##################################################################
]

DANGEROUS_FILES: list[str] = [
    '.env',
    '.env.local',
    '.env.development',
    '.env.production',
    '.env.staging',
    '.env.test',
    '.env.backup',
    '.env.bak',
    'secrets.json',
    'secrets.yaml',
    'secrets.yml',
    'credentials.json',
    'credentials.yaml',
    'credentials.yml',
    'config.json',
    'config.yaml',
    'config.yml',
    'settings.json',
    'local_settings.py',
    'database.yml',
    'id_rsa',
    'id_ed25519',
    'id_dsa',
    'id_ecdsa',
    '*.pem',
    '*.key',
    '*.p12',
    '*.pfx',
    '*.jks',
    'keystore.jks',
    'google-services.json',
    'GoogleService-Info.plist',
    'firebase-adminsdk.json',
    'serviceAccountKey.json',
    'terraform.tfvars',
    '*.tfstate',
    'kubeconfig',
    'kube.config',
    '.npmrc',
    '.pypirc',
    'auth.json',
    'htpasswd',
    '.htpasswd',
    'shadow',
    'passwd',
    'wp-config.php',
]